version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: twitterdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "docker"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: my-weak-password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db